version: "3.9"
services:
  app:
    image: gohandson
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - "8080:80"
