version: "3.9"
services:
  app:
    image: go-playground/go-web-application-dev/handson
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - target=development
    environment:
      TODO_ENV: development
      PORT: 80
    volumes:
      - .:/app
    ports:
      - "8080:80"
